export enum TransactionType {
  'FUNDING' = 'FUNDING',
  'WITHDRAWAL' = 'WITHDRAWAL',
  'ESCROW' = 'ESCROW',
}

export enum TransactionStatus {
  'SETTLED' = 'SETTLED',
  'NOT_SETTLED' = 'NOT_SETTLED',
  'HOLD' = 'HOLD',
  'PAID_SERVICE_PROVIDER' = 'PAID_SERVICE_PROVIDER',
  'REVERSED_TO_CLIENT' = 'REVERSED_TO_CLIENT',
}
