export type IPermissionName =
  | 'Purchase'
  | 'Asset Tracker'
  | 'Suppliers'
  | 'Settings'
  | '+ New Comments'
  | 'Create new supplier'
  | 'Edit users and user permissions'
  | 'Edit groups and group permissions'
  | 'Create suppliers'
  | 'Dashboard'
  | 'Status analytics'
  | 'Product cards'
  | 'Products'
  | 'View products'
  | 'Create new products'
  | 'Export products'
  | 'Delete products'
  | 'Product details'
  | 'General'
  | 'View General'
  | 'Edit General'
  | 'Quotes'
  | 'View Quotes'
  | 'Create/Edit/Delete/Request Quotes'
  | 'Samples'
  | 'View Samples'
  | 'Create/Edit/Delete/Request Samples'
  | 'Content'
  | 'View Content'
  | 'Create/Edit/Delete/Request Content'
  | 'Threads'
  | 'View Threads'
  | 'Create/Edit/Delete Threads'
  | 'Categories'
  | 'View categories'
  | 'Create new categories'
  | 'Edit categories'
  | 'Delete categories'
  | 'Certificates'
  | 'View certificates'
  | 'Create new certificates'
  | 'Edit certificates'
  | 'Delete certificates'
  | 'Workspace'
  | 'Analytics'
  | 'Financial'
  | 'Faulty product'
  | 'Office KPI'
  | 'Workspace Actions'
  | 'Search products'
  | 'Sell Device'
  | 'Receive Device'
  | 'Product Details Actions'
  | 'Add Complaint'
  | 'Add Customer Return'
  | 'Order Parts'
  | 'Send to Auction'
  | 'Change Status'
  | 'User'
  | 'Change Repair Priority'
  | 'Print Label'
  | 'Print Comments'
  | 'Products'
  | 'View products'
  | 'Export products'
  | 'Archive products'
  | 'Product Details'
  | 'General'
  | 'View General'
  | 'Edit General'
  | 'Sold History'
  | 'Returned History'
  | 'Audit Trail'
  | 'Comments'
  | 'View Comments'
  | 'Unlock users'
  | 'Create/Edit Comments'
  | 'Threads'
  | 'View Threads'
  | 'Create/Edit/Delete Threads'
  | 'Change Status'
  | 'User'
  | 'Status'
  | 'Shipped'
  | 'Received'
  | 'Sold'
  | 'Customer Returned'
  | 'Waiting Test'
  | 'Tested'
  | 'Waiting Repair'
  | 'Repaired'
  | 'Return To Supplier'
  | 'Working Pipeline'
  | 'View working pipeline'
  | 'Print Label/Comments'
  | 'Change Repair Priority'
  | 'Part Orders'
  | 'View part orders'
  | 'Create new order'
  | 'Delete orders'
  | 'Export orders'
  | 'View part order tab'
  | 'Edit part order tab'
  | 'Auctions'
  | 'View auctions'
  | 'Send to Auction'
  | 'Export auctions'
  | 'View Auction tab'
  | 'Edit Auction tab'
  | 'Brands'
  | 'View brands'
  | 'Create new brands'
  | 'Edit brands'
  | 'Delete brands'
  | 'Models'
  | 'View models'
  | 'Create new models'
  | 'Edit models'
  | 'Delete models'
  | 'Colours'
  | 'View colours'
  | 'Create new colours'
  | 'Edit colours'
  | 'Delete colours'
  | 'Channels'
  | 'View channels'
  | 'Create new channels'
  | 'Edit channels'
  | 'Delete channels'
  | 'Return Reasons'
  | 'View return reasons'
  | 'Create new return reasons'
  | 'Edit return reasons'
  | 'Delete return reasons'
  | 'Archived Products'
  | 'View archive products'
  | 'Unarchive products'
  | 'Delete archived products'
  | 'View suppliers'
  | 'Edit suppliers'
  | 'Delete suppliers'
  | 'Manage Users'
  | 'View users'
  | 'Create new users'
  | 'Delete users'
  | 'Groups'
  | 'View groups'
  | 'Create new groups'
  | 'Delete groups'
  | 'Locked Users'
  | 'View locked users';
