export class SendNotification {
  name: string;
  type: 'NEW_INIVITATTION';
}

export enum NotificationType {
  'INIVITATION' = 'INIVITATION',
  'WITHDRAWAL' = 'WITHDRAWAL',
  'ACCOUNT_CREDIT' = 'ACCOUNT_CREDIT',
  'ACCOUNT_DEBIT' = 'ACCOUNT_DEBIT',
  'SERVICE_REQUEST_CREDIT' = 'SERVICE_REQUEST_CREDIT',
  'SERVICE_REQUEST_PROPOSAL' = 'SERVICE_REQUEST_PROPOSAL',
  'PROPOSAL_COMPLETE' = 'PROPOSAL_COMPLETE',
  'PROPOSAL_STARTED' = 'PROPOSAL_STARTED',
  'JOB_DISPUTE_RAISED' = 'JOB_DISPUTE_RAISED',
  'JOB_DISPUTE_RESOLVED' = 'JOB_DISPUTE_RESOLVED',
}
